#!/bin/bash


battery_number() {
	local bats=$(acpi -b | sed -r '/rate information unavailable/d; s/^Battery ([0-9]+):.*$/\1/')
	local bat=$(echo $bats | egrep "^${1}$")
	if [[ -z "$1" ]] || [[ -z "$bat" ]]; then
		echo $bats | sed '1q'
	else
		echo $bat
	fi
}

battery_status() {
	acpi -b | sed -r "/rate information unavailable/d; s/^Battery $1: (.*), ([0-9]+)%/\1 \2/; q"
}

BATTERY=$(battery_number $BLOCK_INSTANCE)
if [[ -z "$BATTERY" ]]; then
	exit 0
fi

FULL_STATUS=$(battery_status $BATTERY)
if [[ -z "$FULL_STATUS" ]]; then
	exit 0
fi

STATUS=${FULL_STATUS% *}
LEVEL=${FULL_STATUS#* }

SHORT_TEXT="${LEVEL}%"
case $STATUS in
	"Discharging")
		FULL_TEXT+="$SHORT_TEXT DIS"
		;;
	"Charging")
		FULL_TEXT+="$SHORT_TEXT CHR"
		;;
	"Not Charging")
		FULL_TEXT+="$SHORT_TEXT NCH"
		;;
	*)
		FULL_TEXT+="$SHORT_TEXT"
		;;
esac

echo $FULL_TEXT
echo $SHORT_TEXT

case $STATUS in
	"Discharging")
		if [[ $LEVEL -lt 20 ]]; then
			echo "#FF0000"
		elif [[ $LEVEL -lt 40 ]]; then
			echo "#FFAE00"
		elif [[ $LEVEL -lt 60 ]]; then
			echo "#FFF600"
		else
			echo "#A8FF00"
		fi

		if [[ $LEVEL -lt 5 ]]; then
			exit 33
		fi
		;;
	"Charging")
		echo "#A8FF00"
		;;
	"Not Charging")
		echo "#FF0000"
		if [[ $LEVEL -lt 5 ]]; then
			exit 33
		fi
		;;
	*)
		echo "#FFFFFF"
		;;
esac
