#!/bin/bash
# Install all the dotfiles.

DOT=$(readlink -f "$(dirname $0)")
MODS="${DOT}/modules"

ln -sf "${DOT}/bashrc" ~/.bashrc
ln -sf "${DOT}/bash_logout" ~/.bash_logout
ln -sf "${DOT}/bash_profile" ~/.bash_profile

for MOD in $(ls "$MODS"); do
	MODINS="${MODS}/${MOD}/install"
	test -x "$MODINS" && $MODINS
done

echo "source /etc/profile && source ${DOT}/bashrc"
