#!/bin/bash
# Install all the dotfiles.
git submodule update --init 1>&2

DOT=$(cd "$(dirname "$0")"; pwd)
export PATH="${DOT}/bin:${PATH}"

for MOD in $(ls "$DOT"); do
	INSTALL="$DOT/$MOD/install"
	if [ -x  "$INSTALL" ]; then
		echo "=== install $MOD"
		$INSTALL
	fi
done
