set nocompatible

" plugins
execute pathogen#infect()
filetype plugin indent on

" airline
let g:airline_powerline_fonts = 1

" command-t
noremap <C-f> :CommandTFlush<CR>
let g:CommandTFileScanner = "find"
let g:CommandTTraverseSCM = "pwd"

" tab and indent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
let g:leave_my_textwidth_alone = 1

" honor modeline
set modeline
set modelines=2

" line numbering and scrolling
function! ToggleNumbers()
    if (&relativenumber == 1)
        set number
        set norelativenumber
    else
        set number
        set relativenumber
    endif
endfunction

autocmd BufEnter * set number
autocmd BufEnter * set relativenumber
set cursorline
set scrolloff=3

" key mappings
let mapleader = ","
nnoremap <C-k> <PageUp>
nnoremap <C-j> <PageDown>
nnoremap <C-n> :call ToggleNumbers()<cr>
vnoremap <C-s> :sort<cr>
map <Left> <Nop>
map <Up> <Nop>
map <Down> <Nop>
map <Right> <Nop>

" color settings
set t_Co=256
colorscheme fatedmariner
syntax on

" other settings
set nobackup
set encoding=utf-8
set laststatus=2

" source work settings
if filereadable(expand("~/.work/vimrc"))
    source ~/.work/vimrc
endif
