" plugins
execute pathogen#infect()
filetype plugin indent on

" shared vim config
source ~/.vim/shared.vim

" source work settings
if filereadable(expand("~/.work/vimrc"))
    source ~/.work/vimrc
endif
