#!/bin/bash
if [[ "$(whoami)" != "root" ]]; then
	echo "to install xlock run (with sudo):" >&2
	echo "$ sudo .dot/xlock/install" >&2
	exit 1
fi

cd "$(dirname "$0")"

cp xlock /usr/bin/
cp xlock.service /lib/systemd/system/
systemctl daemon-reload
systemctl enable xlock.service
