#!/bin/bash
rcfile=.xlockrc

lock_with_xlockrc() {
	local home=$(getent passwd "$1" | cut -d: -f6)
	local rcpath="$home/$rcfile"
	test -x "$rcpath" && sudo -u "$1" HOME="$home" DISPLAY="$2" "$rcpath"
}

lock_with_default() {
	sudo -u "$1" DISPLAY="$2" XSECURELOCK_SAVER=saver_xscreensaver /usr/bin/xsecurelock
}

lock_user_display() {
	local user="$USER"
	local display="$DISPLAY"
	echo "lock USER=$user DISPLAY=$display"

	lock_with_xlockrc "$user" "$display" || \
		lock_with_default "$user" "$display"
}

lock_user_display
