#!/bin/bash
# Tools that don't work as scripts.

# Move up the directory tree.
bd() {
	# quickly go back to a parent directory
	test "${1-}" == "" && return 2
	local newpwd=$(echo $(pwd) | sed 's|\(.*/'$1'[^/]*/\).*|\1|')
	local index=$(echo "$newpwd" | awk '{ print index($1,"/'$1'"); }')
	test "$index" -eq 0 && return 1
	cd "$newpwd"
}

# Change to a sandbox directory.
sb() {
	local sandbox="$HOME/Sandbox"
	local default="."
    which trycd &> /dev/null || return
	test -z "${1-}" && cd "${sandbox}/${default}" && return
    eval `trycd "$sandbox" "${1-}" go-`
}

# Create and enter a Python virtualenv.
venv() {
	local name=${1:-.venv}
	if ! [ -e "$name" ]; then
		virtualenv --no-site-packages "$name"
		source "$name/bin/activate"
		pip install --upgrade pip
	else
		source "$name/bin/activate"
	fi
}
