#!/bin/bash

function ta {
  if tmux list-sessions &> /dev/null; then
    tmux attach-session
  else
    tmux new-session
  fi
}

function tt {
  tmux new-session "$@"
}

function td {
    tmux attach-session -d
}
