# if not running interactively, don't do anything
case $- in
*i*)
	;;
*)
	return
	;;
esac

clear

[[ -f /etc/profile ]] && source /etc/profile

umask 0027

DOT="${HOME}/.dot"
PATH="${DOT}/bin:~/bin:/~/Sandbox/bin:/sbin:/usr/sbin:${PATH}"
PS1='\[\033[01;32m\]\w \[\033[01;34m\]\$\[\033[00m\] '

# reset terminal size on window change
shopt -s checkwinsize

# include snippets
for include in $(ls "$DOT/bash/include"); do
	. "$DOT/bash/include/$include"
done

[[ -f ~/.work/bashrc ]] && source ~/.work/bashrc

if grep -q Microsoft /proc/version; then
	/usr/bin/keychain --nogui $HOME/.ssh/id_rsa
	. $HOME/.keychain/$HOSTNAME-sh
fi

set -o vi
bind -m vi-insert "\C-l":clear-screen

stty start ""
stty stop ""

export PATH

alias cd.='cd `pwd -P`'
alias rebash="exec bash"
