# if not running interactively, don't do anything
case $- in
*i*)
	;;
*)
	return
	;;
esac

[[ -f /etc/profile ]] && source /etc/profile

umask 0027

DOT="${HOME}/.dot"
PATH="${DOT}/bin:~/Sandbox/bin:/sbin:/usr/sbin:${PATH}"
PS1='\[\033[01;32m\]\w \[\033[01;34m\]\$\[\033[00m\] '

# reset terminal size on window change
shopt -s checkwinsize

# include snippets
for include in $(ls "$DOT/bash/include"); do
	. "$DOT/bash/include/$include"
done

[[ -f ~/.work/bashrc ]] && source ~/.work/bashrc

set -o vi
bind -m vi-insert "\C-l":clear-screen

stty start ""
stty stop ""

export PATH

[[ $TERM == "screen" ]] || exec tmux new-session
