[[ -f /etc/profile ]] && source /etc/profile

umask 0027

DOT="${HOME}/.dot"
PATH="${DOT}/bin:~/.virtualenv27/bin:~/Sandbox/bin:/sbin:/usr/sbin:${PATH}"
PS1='\[\033[01;32m\]\w \[\033[01;34m\]\$\[\033[00m\] '
EDITOR="/usr/bin/vim"

# include snippets
for include in $(ls "$DOT/bash/include"); do
	. "$DOT/bash/include/$include"
done

[[ -f ~/Work/.bashrc ]] && source ~/Work/.bashrc

set -o vi
bind -m vi-insert "\C-l":clear-screen
alias grep="grep -s --color"
alias egrep="egrep --color"
alias ls="ls --color"

stty start ""
stty stop ""

export PATH EDITOR
